I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 18, in script
    show Patricia ypos 20
Exception: Image 'Patricia' does not accept attributes 'ypos 20'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 18, in script
    show Patricia ypos 20
  File "C:\Program Files\RenPy 8.2.3-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Program Files\RenPy 8.2.3-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Program Files\RenPy 8.2.3-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Program Files\RenPy 8.2.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Program Files\RenPy 8.2.3-sdk\renpy\display\transform.py", line 1089, in _duplicate
    args.extraneous()
  File "C:\Program Files\RenPy 8.2.3-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'Patricia' does not accept attributes 'ypos 20'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
WGJ 2024 1.0
Sun Aug 11 01:31:32 2024
